### ISSUE TITLE
Crash when scanning barcode / qrcode (android)

### ISSUE THREAD

**Issue by bdaykid** [dns-technologies/mlkit_scanner#7]
Hello again. This happen when I try to integrate the lib into my own project. Running the example project does not produce this error.

    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/barcode/Barcode;
        at com.dns_technologies.mlkit_scanner.analyzer.MlSingleBarcodeAnalyzer.onSuccessScan(MlSingleBarcodeAnalyzer.kt:102)
        at com.dns_technologies.mlkit_scanner.analyzer.MlSingleBarcodeAnalyzer.$r8$lambda$Y-tNOhaaHvcyOtTUkuHQ-dP33cw(MlSingleBarcodeAnalyzer.kt)
        at com.dns_technologies.mlkit_scanner.analyzer.MlSingleBarcodeAnalyzer$$ExternalSyntheticLambda2.onSuccess(D8$$SyntheticClass)
        at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6410)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.mlkit.vision.barcode.Barcode" on path: DexPathList[[zip file "/data/app/my.app.nex-2/base.apk"],nativeLibraryDirectories=[/data/app/my.app.nex-2/lib/arm64, /data/app/my.app.nex-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.dns_technologies.mlkit_scanner.analyzer.MlSingleBarcodeAnalyzer.onSuccessScan(MlSingleBarcodeAnalyzer.kt:102) 
        at com.dns_technologies.mlkit_scanner.analyzer.MlSingleBarcodeAnalyzer.$r8$lambda$Y-tNOhaaHvcyOtTUkuHQ-dP33cw(MlSingleBarcodeAnalyzer.kt) 
        at com.dns_technologies.mlkit_scanner.analyzer.MlSingleBarcodeAnalyzer$$ExternalSyntheticLambda2.onSuccess(D8$$SyntheticClass) 
        at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:1) 
        at android.os.Handler.handleCallback(Handler.java:836) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:203) 
        at android.app.ActivityThread.main(ActivityThread.java:6410) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

**Comment by yeminsoe** [comment]
I also faced the same issues.

**Comment by skrjt** [comment]
Hi, @bdaykid , @yeminsoe !
This looks like a problem with gradle caches, have you tried cleaning them?

**Comment by irfnyas** [comment]
I also faced this but with different error

```
E/AndroidRuntime( 6115): kotlin.UninitializedPropertyAccessException: lateinit property center has not been initialized
E/AndroidRuntime( 6115): 	at com.dns_technologies.mlkit_scanner.CenterFocusView.lockMovementAnimation(CenterFocusView.kt:126)
E/AndroidRuntime( 6115): 	at com.dns_technologies.mlkit_scanner.CenterFocusView.buildLockAnimation(CenterFocusView.kt:118)
E/AndroidRuntime( 6115): 	at com.dns_technologies.mlkit_scanner.CenterFocusView.lockFocus(CenterFocusView.kt:106)
E/AndroidRuntime( 6115): 	at com.dns_technologies.mlkit_scanner.CenterFocusView.access$lockFocus(CenterFocusView.kt:12)
E/AndroidRuntime( 6115): 	at com.dns_technologies.mlkit_scanner.CenterFocusView$createGestureDetector$1.onLongPress(CenterFocusView.kt:63)
E/AndroidRuntime( 6115): 	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:770)
E/AndroidRuntime( 6115): 	at android.view.GestureDetector.-wrap0(GestureDetector.java)
E/AndroidRuntime( 6115): 	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
E/AndroidRuntime( 6115): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime( 6115): 	at android.os.Looper.loop(Looper.java:203)
E/AndroidRuntime( 6115): 	at android.app.ActivityThread.main(ActivityThread.java:6364)
E/AndroidRuntime( 6115): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6115): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1076)
E/AndroidRuntime( 6115): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
```

**Comment by daga-hiwot** [comment]
@skrjt it is not gradle cache. anyone who solved this problem?

**Comment by skrjt** [comment]
Was fixed in https://github.com/dns-technologies/mlkit_scanner/pull/22
